swagger: "2.0"
info:
  description: "This API allows users to create a new topic by providing the necessary information in a JSON payload."
  version: "1.0.0"
  title: "Topic Management API"

host: "localhost"
basePath: "/api/v1"

paths:
  /topics:
    post:
      summary: "Create a new topic"
      description: |
        This route allows the creation of a new topic. It accepts a JSON payload containing
        the topic's name and optional parent_id. The topic name must be a string with a 
        maximum length of 128 characters. The parent_id, if provided, must correspond to an 
        existing parent topic. If any input is invalid or a duplicate topic is found, an error 
        message will be returned.

      operationId: "createTopic"
      tags:
        - "Topics"
      
      parameters:
        - name: "Authorization"
          in: "header"
          description: "JWT authentication token required for accessing this endpoint"
          required: true
          type: "string"
          
        - name: "topic"
          in: "body"
          description: "The topic to be created. Must include a name and optional parent_id."
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                description: "The name of the topic"
              parent_id:
                type: "integer"
                description: "The ID of the parent topic (optional)"
            
      responses:
        201:
          description: "Topic created successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Topic added successfully"
              topic:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: "The unique ID of the topic"
                  name:
                    type: "string"
                    description: "The name of the topic"
                  parent_id:
                    type: "integer"
                    description: "The ID of the parent topic (optional)"
                  created_at:
                    type: "string"
                    format: "date-time"
                    description: "The timestamp when the topic was created"
                  updated_at:
                    type: "string"
                    format: "date-time"
                    description: "The timestamp when the topic was last updated"
          examples:
            application/json:
              {
                "message": "Topic added successfully",
                "topic": {
                  "id": "123",
                  "name": "Science",
                  "parent_id": null,
                  "created_at": "2025-01-01T12:00:00Z",
                  "updated_at": "2025-01-01T12:00:00Z"
                }
              }
        
        400:
          description: "Bad request. Missing or invalid input data."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Missing topic name"
          examples:
            application/json:
              {
                "message": "Missing topic name"
              }

        404:
          description: "Parent topic not found."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Parent not found"
          examples:
            application/json:
              {
                "message": "Parent not found"
              }

        409:
          description: "Conflict. The topic name already exists."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Topic name already exists!"
          examples:
            application/json:
              {
                "message": "Topic name already exists!"
              }

        401:
          description: "Unauthorized. Missing or invalid JWT token."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Missing or invalid JWT token"
          examples:
            application/json:
              {
                "message": "Missing or invalid JWT token"
              }

securityDefinitions:
  jwtAuth:
    type: "apiKey"
    in: "header"
    name: "Authorization"
    description: "JWT authentication token"
