---
swagger: '2.0'
info:
  title: 'Topic API'
  description: 'API for retrieving topics by their name'
  version: '1.0.0'
host: 'localhost:5000'
basePath: '/api/v1'
schemes:
  - 'http'
paths:
  /topics/name/{topic_name}:
    get:
      summary: 'Get a specific topic by name'
      description: |
        This route retrieves a single topic based on the provided topic name.
        The name is formatted to title case before querying the database.
      operationId: 'getTopicByName'
      tags:
        - 'Topic'
      parameters:
        - in: 'path'
          name: 'topic_name'
          type: 'string'
          required: true
          description: 'The name of the topic to retrieve'
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 'Topic found successfully'
          schema:
            type: 'object'
            example:
              {
                "message": "Topic retrieved successfully",
                "topic": {
                  "id": "12345",
                  "name": "Math",
                  "parent_id": 1,
                  "created_at": "2025-01-01T12:00:00Z",
                  "updated_at": "2025-01-01T12:00:00Z"
                }
              }
        '404':
          description: 'Topic not found'
          schema:
            type: 'object'
            example:
              {
                "message": "Topic not found"
              }
        '400':
          description: 'Bad request - Invalid topic name format'
          schema:
            type: 'object'
            example:
              {
                "message": "Topic name is required"
              }
        '500':
          description: 'Internal Server Error'
          schema:
            type: 'object'
            example:
              {
                "message": "An unexpected error occurred"
              }

definitions:
  Topic:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '12345'
      name:
        type: 'string'
        example: 'Math'
      parent_id:
        type: 'integer'
        example: 1
      created_at:
        type: 'string'
        format: 'date-time'
        example: '2025-01-01T12:00:00Z'
      updated_at:
        type: 'string'
        format: 'date-time'
        example: '2025-01-01T12:00:00Z'
  securityDefinitions:
    BearerAuth:
      type: 'apiKey'
      in: 'header'
      name: 'Authorization'
      description: 'JWT token for authenticating requests'
