swagger: "2.0"
info:
  title: "QuizyPal API"
  description: "API for handling password reset using a reset token."
  version: "1.0.0"
paths:
  /api/v1/reset-password/{token}:
    post:
      summary: "Reset password using a reset token"
      description: |
        This endpoint allows users to reset their password by providing a valid reset token. 
        The token must be valid and not expired. The user must also provide a new password 
        in the request body.

        **Important Notes:**
        - The reset token is sent to the user's email as part of the forgot password process.
        - The token is time-limited and will expire after a specific duration.
        - A successful password reset clears the reset token and expiration timestamp.

      parameters:
        - name: "token"
          in: "path"
          required: true
          type: "string"
          description: "The reset token sent to the user's email."
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        - in: "body"
          name: "body"
          description: "JSON object containing the new password."
          required: true
          schema:
            type: "object"
            required:
              - "new_password"
            properties:
              new_password:
                type: "string"
                description: "The new password to be set for the user."
                example: "SecureNewPassword123!"
      responses:
        200:
          description: "Password successfully reset."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                description: "Confirmation message for successful password reset."
                example: "Password reset successful."
        400:
          description: "Bad request due to invalid token, expired token, or missing data."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                description: "Error message describing the issue."
                example: "Invalid or expired token"
        500:
          description: "Internal server error."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                description: "Error message indicating an unexpected server issue."
                example: "An unexpected error occurred"
definitions:
  Token:
    type: "string"
    description: "Reset token used for password reset."
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
